# Generated by Django 4.2.30 on 2026-06-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='local_market_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='local market Price', max_digits=10, null=True),
        ),
    ]
