# Generated by Django 4.2.30 on 2026-06-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_local_market_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='styling_tips',
            field=models.TextField(blank=True, help_text='Styling tips shown to customers on product page', null=True),
        ),
    ]
