# Generated by Django 4.2.30 on 2026-06-14 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_cancel_reason_order_cancelled_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_hostel',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_room',
        ),
    ]
