# Generated by Django 4.2.30 on 2026-06-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_order_delivery_hostel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='gender',
            field=models.CharField(choices=[('all', 'All'), ('girls', 'Girls'), ('boys', 'Boys')], default='girls', max_length=10),
        ),
    ]
