# Generated by Django 4.2.30 on 2026-06-23 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_razorpay_order_id_order_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='referral_reward_given',
            field=models.BooleanField(default=False),
        ),
    ]
