# Generated by Django 4.2.30 on 2026-06-24 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_order_referral_reward_given'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_label', models.CharField(help_text='e.g. S, M, L, 2.2, 2.4, 30, 32, Free Size', max_length=50)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=0, help_text='Controls display order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='store.product')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
