# Generated by Django 4.2.30 on 2026-06-24 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_productsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.productsize'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size_label',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
