# Generated by Django 4.2.30 on 2026-06-25 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_cart_size_orderitem_size_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='size',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='size_label',
        ),
        migrations.DeleteModel(
            name='ProductSize',
        ),
    ]
