# Generated by Django 4.2.30 on 2026-06-26 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_cart_size_remove_orderitem_size_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size_label',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_label', models.CharField(help_text='e.g. S, M, L, 2.2, 2.4, 30, 32', max_length=50)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=0, help_text='Controls display order, lowest first')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='store.product')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.productsize'),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user', 'product', 'size'), ('session_key', 'product', 'size')},
        ),
    ]
