# Generated by Django 4.2.30 on 2026-06-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_orderitem_size_label_productsize_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CODPincode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(help_text='e.g. 751001', max_length=10, unique=True)),
                ('area_note', models.CharField(blank=True, help_text="Optional label, e.g. 'Bhubaneswar - Patia'", max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'COD Allowed Pincode',
                'verbose_name_plural': 'COD Allowed Pincodes',
                'ordering': ['pincode'],
            },
        ),
    ]
