services:
  - type: web
    name: cladly
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    preDeployCommand: |
      python manage.py migrate --noinput
      python manage.py createcachetable
      python manage.py collectstatic --noinput
    startCommand: gunicorn cladly.wsgi --log-file -
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.11"
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "0"
      - key: ALLOWED_HOSTS
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false